import type { VocabEntry } from './labTypes'

export const featuredLabEntries: VocabEntry[] = [
  {
    id: 'featured-001',
    word: '勉強する',
    kana: 'べんきょうする',
    level: 'N5',
    meaningZh: '学习，用功',
    meaningEn: 'to study',
    detailZh: '表示系统性地学习、备考或主动投入时间掌握知识。',
    source: 'Lab Featured Deck',
    track: 'featured',
    partOfSpeech: 'サ变动词',
    exampleJa: '毎晩一時間、日本語を勉強しています。',
    exampleZh: '我每天晚上学习一个小时日语。',
    notes: ['适合和时间表达一起记，例如「毎日」「毎晩」。'],
  },
  {
    id: 'featured-002',
    word: '大丈夫',
    kana: 'だいじょうぶ',
    level: 'N5',
    meaningZh: '没问题，没关系；可靠，稳妥',
    meaningEn: 'all right, okay',
    detailZh: '既可以表示“不要紧”，也可以表示状态稳定、可以放心。',
    source: 'Lab Featured Deck',
    track: 'featured',
    partOfSpeech: '形容动词',
    exampleJa: 'まだ時間があるので、大丈夫です。',
    exampleZh: '还有时间，所以没问题。',
    notes: ['口语里非常高频，要结合语境区分“放心”和“没关系”。'],
  },
  {
    id: 'featured-003',
    word: '相変わらず',
    kana: 'あいかわらず',
    level: 'N2',
    meaningZh: '照旧，依然，还是老样子',
    meaningEn: 'as usual',
    detailZh: '常用来描述状态没有变化，语气中常带熟悉感。',
    source: 'Lab Featured Deck',
    track: 'featured',
    partOfSpeech: '副词',
    exampleJa: '彼は相変わらず朝が早いです。',
    exampleZh: '他还是和以前一样起得很早。',
    notes: ['经常和习惯、状态、性格类表达一起出现。'],
  },
  {
    id: 'featured-004',
    word: '影響',
    kana: 'えいきょう',
    level: 'N3',
    meaningZh: '影响',
    meaningEn: 'influence, effect',
    detailZh: '既可以表示抽象影响，也可以表示现实后果，常和「受ける」「与える」搭配。',
    source: 'Lab Featured Deck',
    track: 'featured',
    partOfSpeech: '名词 / サ变名词',
    exampleJa: '天気の変化が体調に影響します。',
    exampleZh: '天气变化会影响身体状态。',
    notes: ['建议顺手记住「影響を受ける」「影響を与える」。'],
  },
  {
    id: 'featured-005',
    word: '改善',
    kana: 'かいぜん',
    level: 'N3',
    meaningZh: '改善，优化',
    meaningEn: 'improvement',
    detailZh: '偏向让事情变得更好，常用于学习方法、产品体验和工作流程。',
    source: 'Lab Featured Deck',
    track: 'featured',
    partOfSpeech: '名词 / サ变名词',
    exampleJa: '学習の流れを少しずつ改善しています。',
    exampleZh: '我正在一点点优化学习流程。',
    notes: ['和产品、项目、流程相关的语境里很常见。'],
  },
  {
    id: 'featured-006',
    word: '仮説',
    kana: 'かせつ',
    level: 'N2',
    meaningZh: '假设，假说',
    meaningEn: 'hypothesis',
    detailZh: '多用于研究、实验和分析场景，表示尚待验证的判断。',
    source: 'Lab Featured Deck',
    track: 'featured',
    partOfSpeech: '名词',
    exampleJa: 'まず仮説を立ててから検証します。',
    exampleZh: '先提出假设，再去验证。',
    notes: ['常和「立てる」「検証する」一起记。'],
  },
  {
    id: 'featured-007',
    word: '提案',
    kana: 'ていあん',
    level: 'N3',
    meaningZh: '提案，建议',
    meaningEn: 'proposal, suggestion',
    detailZh: '适合用于会议、协作和产品方案讨论，也可以用于较正式的建议。',
    source: 'Lab Featured Deck',
    track: 'featured',
    partOfSpeech: '名词 / サ变名词',
    exampleJa: '来週の会議で新しい案を提案します。',
    exampleZh: '我会在下周的会议上提出新的方案。',
    notes: ['和「提案する」「提案を出す」都很常见。'],
  },
  {
    id: 'featured-008',
    word: '選択',
    kana: 'せんたく',
    level: 'N3',
    meaningZh: '选择',
    meaningEn: 'selection, choice',
    detailZh: '强调在多个选项中做取舍，也经常用于产品和决策语境。',
    source: 'Lab Featured Deck',
    track: 'featured',
    partOfSpeech: '名词 / サ变名词',
    exampleJa: '情報が多いほど選択が難しくなります。',
    exampleZh: '信息越多，选择就越难。',
    notes: ['适合和「比較」「判断」一起记成决策词组。'],
  },
  {
    id: 'featured-009',
    word: '復習',
    kana: 'ふくしゅう',
    level: 'N4',
    meaningZh: '复习',
    meaningEn: 'review',
    detailZh: '强调对已经学过的内容重新回看和巩固，是学习闭环里的核心动作。',
    source: 'Lab Featured Deck',
    track: 'featured',
    partOfSpeech: '名词 / サ变名词',
    exampleJa: '今日は昨日の単語を復習します。',
    exampleZh: '今天我要复习昨天学过的单词。',
    notes: ['和日期、频率表达一起记会更实用。'],
  },
  {
    id: 'featured-010',
    word: '柔らかい',
    kana: 'やわらかい',
    level: 'N4',
    meaningZh: '柔软；柔和',
    meaningEn: 'soft',
    detailZh: '既可以形容物理上的柔软，也可以形容语气和表达更温和。',
    source: 'Lab Featured Deck',
    track: 'featured',
    partOfSpeech: 'い形容词',
    exampleJa: '柔らかい言い方のほうが伝わりやすいです。',
    exampleZh: '更柔和的表达方式更容易被接受。',
    notes: ['可以顺手记住「言い方」「表現」这些搭配。'],
  },
  {
    id: 'featured-011',
    word: '解決',
    kana: 'かいけつ',
    level: 'N3',
    meaningZh: '解决',
    meaningEn: 'solution, resolution',
    detailZh: '表示问题被处理、冲突被化解，适合工作、学习和协作场景。',
    source: 'Lab Featured Deck',
    track: 'featured',
    partOfSpeech: '名词 / サ变名词',
    exampleJa: '小さな問題でも早めに解決したほうがいいです。',
    exampleZh: '即使是小问题，也最好尽早解决。',
    notes: ['高频搭配是「問題を解決する」。'],
  },
  {
    id: 'featured-012',
    word: '継続',
    kana: 'けいぞく',
    level: 'N2',
    meaningZh: '持续，坚持',
    meaningEn: 'continuation',
    detailZh: '强调动作、计划或者状态的延续，是学习和项目推进里非常常见的核心词。',
    source: 'Lab Featured Deck',
    track: 'featured',
    partOfSpeech: '名词 / サ变名词',
    exampleJa: '短い時間でも継続することが大切です。',
    exampleZh: '哪怕时间不长，坚持下去也很重要。',
    notes: ['适合和「努力」「習慣」一起记。'],
  },
]

export const labQuickPresets = [
  {
    id: 'preset-featured',
    label: '精选词卡',
    description: '先从有例句、有词性、可以直接学习的词卡开始。',
    sourceMode: 'featured',
    levelFilter: 'ALL',
    keyword: '',
  },
  {
    id: 'preset-n5',
    label: 'N5 基础',
    description: '从入门高频词开始，适合建立第一轮词感。',
    sourceMode: 'n5',
    levelFilter: 'N5',
    keyword: '',
  },
  {
    id: 'preset-jlpt',
    label: 'JLPT 扩展',
    description: '切到 JLPT 10K，查看更大的检索范围。',
    sourceMode: 'jlpt10k',
    levelFilter: 'ALL',
    keyword: '',
  },
  {
    id: 'preset-kaoyan',
    label: '考研高频',
    description: '把考研常见词单独拉出来强化。',
    sourceMode: 'kaoyan3500',
    levelFilter: '考研',
    keyword: '',
  },
]

export const labFallbackCatalog = {
  totalLabel: '17K+',
  totalDescription: '后台会继续接入更大的多源词库，当前先给你可以直接开始学习的精选词卡。',
}
